import Head from 'next/head'
import styles from '../styles/Home.module.css'

import PageConfig from '../models/PageConfig'
import dbConnect from '../lib/dbConnect'


export default function Home({ pageConfig }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>sehmim.al</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPage {...pageConfig} />

    </div>
  )
}

export function LandingPage({ logo, social_links, arrow }) {
  return (
    <div className={styles.landingPageWrapper}>
      <Logo logo={logo} />
      <SocialLinks social_links={social_links} />
      <Arrow arrow={arrow} />
    </div>
  )
}


function Logo({ logo }) {
  const { url } = logo

  return (
    <div className={styles.logoWrapper}>
      <img className={styles.logo} src={url} />
    </div>
  )
}

function SocialLinks({ social_links }) {

  return (
    <div className={styles.socialWrapper}>
      {
        social_links.map(({ icon, link }) => {
          return (
            <a className={styles.socialWrapperEach}>
              <img className={styles.socialImg} src={icon} />
            </a>
          )
        })
      }
    </div>
  )
}

function Arrow({ arrow }) {
  const { hide } = arrow

  let render = null;

  if (!hide) {
    render = <div >
      <div class={styles.arrow}></div>
    </div>
  }

  return render

}

export async function getServerSideProps() {
  try {
    await dbConnect()

  } catch (err) {
    console.log(err)
  }

  const rawQuotes = await PageConfig.findOne({ "userID": "1" })

  const dataString = JSON.stringify(rawQuotes)
  const pageConfig = JSON.parse(dataString)

  return {
    props: { pageConfig }
  }
}